# Generated by Django 5.0.3 on 2025-04-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_service', '0015_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='service_man',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
